service:
  name: aws-node-typescript-apollo-lambda

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  timeout: 15

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
  test:
    handler: src/handler.test
    events:
      - sqs: arn:aws:sqs:us-east-2:577813270602:TransactionQueue
      - http:
          path: test
          method: get
          cors: true
